function fig = MotorGenerator2_Component_plotResults(nvpairs)
% plots the simulation result.

% Copyright 2022 The MathWorks, Inc.

arguments
  nvpairs.SimData timetable
  nvpairs.FigureHeight (1,1) {mustBePositive} = 300
end

sigNames = [ ...
  "MG2 torque command", ...
  "Brake force", ...
  "Road grade", ...
  "G force", ...
  "MG2 speed", ...
  "MG2 torque", ...
  "MG2 power rate", ...
  "MG2 temperature", ...
  "MG2 current", ...
  "MG2 voltage", ...
  "MG2 mechanical power", ...
  "Battery SOC", ...
  "Vehicle speed kph", ...
  "Vehicle speed mph", ...
  "Travelled distance", ...
  "Road inclination", ...
  "Battery voltage", ...
  "Battery current", ...
  "Battery power loss", ...
  "Battery charge", ...
  "Battery power", ...
  "MG2 electrical losses", ...
  "Axle speed" ];

for i = 1 : numel(sigNames)
  fig = plotSimulationResultSignal(SimData = nvpairs.SimData, SignalName = sigNames(i));
  fig.Position(4) = nvpairs.FigureHeight;
end

end  % function
