function fig = PowerSplitGeartrain_Component_plotResults(nvpairs)
% plots the simulation result.

% Copyright 2022 The MathWorks, Inc.

arguments
  nvpairs.SimData timetable
  nvpairs.FigureHeight (1,1) {mustBePositive} = 300
end

sigNames = [ ...
  "Axle clutch", ...
  "Vehicle speed input", ...
  "Vehicle speed", ...
  "Axle speed input", ...
  "Axle speed", ...
  "MG2 clutch", ...
  "MG1 clutch", ...
  "Engine clutch", ...
  "MG2 speed input", ...
  "MG1 speed input", ...
  "Engine speed input", ...
  "MG2 speed", ...
  "MG1 speed", ...
  "Engine speed" ];

for i = 1 : numel(sigNames)
  fig = plotSimulationResultSignal(SimData = nvpairs.SimData, SignalName = sigNames(i));
  fig.Position(4) = nvpairs.FigureHeight;
end

end  % function
