function fig = PowerSplitDriveUnit_Component_plotResults(nvpairs)
% plots the simulation result.

% Copyright 2022 The MathWorks, Inc.

arguments
  nvpairs.SimData timetable
  nvpairs.FigureHeight (1,1) {mustBePositive} = 300
end

sigNames = [ ...
  "MG2 torque command", ...
  "MG2 torque", ...
  "MG1 torque command", ...
  "MG1 torque", ...
  "Engine torque command", ...
  "Engine torque", ...
  "MG2 speed", ...
  "MG1 speed", ...
  "Engine speed", ...
  "MG2 mechanical power", ...
  "MG1 mechanical power", ...
  "Engine power", ...
  "Vehicle speed kph", ...
  "Vehicle speed mph", ...
  "MG2 temperature", ...
  "MG1 temperature", ...
  "Battery voltage", ...
  "Battery current", ...
  "Battery power", ...
  "Battery SOC", ...
  "Brake force", ...
  "Road grade", ...
  "G force" ];

for i = 1 : numel(sigNames)
  fig = plotSimulationResultSignal(SimData = nvpairs.SimData, SignalName = sigNames(i));
  fig.Position(4) = nvpairs.FigureHeight;
end

end  % function
