function fig = MotorGenerator1_Component_plotResults(nvpairs)
% plots the simulation result.

% Copyright 2022 The MathWorks, Inc.

arguments
  nvpairs.SimData timetable
  nvpairs.FigureHeight (1,1) {mustBePositive} = 300
end

sigNames = [ ...
  "MG1 torque command", ...
  "MG1 torque", ...
  "MG1 mechanical power", ...
  "MG1 electrical power", ...
  "Engine torque command", ...
  "Engine torque", ...
  "Engine power", ...
  "Battery power", ...
  "MG1 speed", ...
  "Engine speed", ...
  "MG1 electrical loss", ...
  "MG1 temperature", ...
  "MG1 current", ...
  "MG1 voltage", ...
  "MG1 power rate", ...
  "Battery SOC" ];

for i = 1 : numel(sigNames)
  fig = plotSimulationResultSignal(SimData = nvpairs.SimData, SignalName = sigNames(i));
  fig.Position(4) = nvpairs.FigureHeight;
end

end  % function
